/* ARGO Direct translations. Italian remains the canonical kitchen language. */
(function () {
  const languages = {
    it: { label: 'Italiano', flag: '🇮🇹' },
    en: { label: 'English', flag: '🇬🇧' },
    el: { label: 'Ελληνικά', flag: '🇬🇷' },
    es: { label: 'Español', flag: '🇪🇸' },
    de: { label: 'Deutsch', flag: '🇩🇪' },
    fr: { label: 'Français', flag: '🇫🇷' }
  };

  const ui = {
    it: {
      site: 'Sito', title: 'Ordina e ritira da ARGO', subtitle: "Scegli, personalizza e invia l'ordine direttamente al locale.",
      pickup: 'Solo ritiro dal locale', delivery: 'Per la consegna a domicilio usa Deliveroo o Just Eat dalla pagina principale.',
      today_offer: 'OFFERTA DI OGGI · SOLO RITIRO ARGO DIRECT', use_offer: 'USA QUESTA OFFERTA', your_order: 'Il tuo ordine', empty_cart: 'Il carrello è vuoto',
      promo_code: 'Codice sconto', apply: 'APPLICA', subtotal: 'Subtotale', discount: 'Sconto', total: 'Totale', continue: 'CONTINUA', all: 'Tutto',
      customize: 'PERSONALIZZA +', add: '+ AGGIUNGI', unavailable_price: 'Prezzo temporaneamente non disponibile', customize_title: 'Personalizza', item_note: 'Nota per questo articolo',
      item_note_example: 'Es. ben cotto, tagliato a metà...', cancel: 'ANNULLA', add_item: 'AGGIUNGI', order_title: "Completa l'ordine", name: 'Nome *', phone: 'Telefono *',
      email: 'Email', order_type: 'Tipo ordine', pickup_value: 'Ritiro dal locale', payment: 'Pagamento', pay_pickup: 'Al ritiro', desired_time: 'Ora desiderata',
      time_hint: 'Il primo orario disponibile è tra 30 minuti.', order_notes: 'Note ordine', send_order: 'INVIA ORDINE', sending: 'INVIO…', note: 'Nota',
      required: 'Nome e telefono sono obbligatori.', time_error: 'Il ritiro deve essere almeno 30 minuti da adesso.', promo_check: 'Controlla il codice sconto prima di inviare.',
      order_error: 'Errore invio ordine. Riprova o chiamaci.', promo_expired: 'Il codice sconto non è più valido. Riprova.', received: 'ricevuto', wait_confirm: 'Attendi la conferma del locale.',
      too_many: 'Troppe opzioni selezionate.', emergency_alert: 'Il menu di emergenza è solo consultazione. Riprova tra poco per inviare l’ordine.',
      emergency_note: 'Menu di emergenza in sola consultazione. Prezzi e ordini tornano disponibili appena il servizio live viene ripristinato.',
      menu_unavailable: 'Menu momentaneamente non disponibile.', retry_soon: 'Menu non disponibile. Riprova tra poco.', add_products: 'Aggiungi prima dei prodotti.',
      min_order: 'Ordine minimo {amount} per questo codice.', wrong_day: 'Questo codice non è valido oggi.', first_only: 'BENVENUTO è riservato al primo ordine diretto.',
      phone_first: 'Inserisci il telefono per usare BENVENUTO.', max_uses: 'Questo codice ha raggiunto il limite di utilizzi.', used_offer: 'Hai già usato questa offerta.', invalid_code: 'Codice non valido o scaduto.',
      savings: 'risparmi {amount}', promo_main: '{discount} sul ritiro diretto da ARGO', promo_meta: "Ordine minimo {amount}. L'offerta vale solo su ARGO Direct, non su Deliveroo o Just Eat.",
      promo_start: 'Aggiungi prodotti fino a {amount} per usare il codice {code}.', promo_left: 'Ti mancano {amount} per ottenere {discount}.', promo_ready: '✓ Hai raggiunto la soglia. Applica {code} e risparmia.', language: 'Lingua'
    },
    en: {
      site: 'Website', title: 'Order and pick up at ARGO', subtitle: 'Choose, customise and send your order directly to the restaurant.',
      pickup: 'Collection only', delivery: 'For delivery, use Deliveroo or Just Eat from the main page.', today_offer: "TODAY'S OFFER · ARGO DIRECT COLLECTION ONLY", use_offer: 'USE THIS OFFER',
      your_order: 'Your order', empty_cart: 'Your basket is empty', promo_code: 'Discount code', apply: 'APPLY', subtotal: 'Subtotal', discount: 'Discount', total: 'Total', continue: 'CONTINUE', all: 'All',
      customize: 'CUSTOMISE +', add: '+ ADD', unavailable_price: 'Price temporarily unavailable', customize_title: 'Customise', item_note: 'Note for this item', item_note_example: 'E.g. well done, cut in half...',
      cancel: 'CANCEL', add_item: 'ADD', order_title: 'Complete your order', name: 'Name *', phone: 'Phone *', email: 'Email', order_type: 'Order type', pickup_value: 'Collect from ARGO',
      payment: 'Payment', pay_pickup: 'Pay on collection', desired_time: 'Preferred time', time_hint: 'The first available time is in 30 minutes.', order_notes: 'Order notes', send_order: 'SEND ORDER', sending: 'SENDING…', note: 'Note',
      required: 'Name and phone are required.', time_error: 'Collection must be at least 30 minutes from now.', promo_check: 'Check the discount code before sending.', order_error: 'Could not send the order. Try again or call us.',
      promo_expired: 'The discount code is no longer valid. Try again.', received: 'received', wait_confirm: 'Please wait for confirmation from ARGO.', too_many: 'Too many options selected.',
      emergency_alert: 'The emergency menu is view-only. Try again shortly to place your order.', emergency_note: 'Emergency view-only menu. Prices and ordering will return when the live service is restored.',
      menu_unavailable: 'Menu temporarily unavailable.', retry_soon: 'Menu unavailable. Please try again shortly.', add_products: 'Add products first.', min_order: 'Minimum order {amount} for this code.', wrong_day: 'This code is not valid today.',
      first_only: 'BENVENUTO is only for your first direct order.', phone_first: 'Enter your phone number to use BENVENUTO.', max_uses: 'This code has reached its usage limit.', used_offer: 'You have already used this offer.', invalid_code: 'Invalid or expired code.',
      savings: 'you save {amount}', promo_main: '{discount} on collection orders from ARGO', promo_meta: 'Minimum order {amount}. This offer is valid only on ARGO Direct, not on Deliveroo or Just Eat.',
      promo_start: 'Add products up to {amount} to use code {code}.', promo_left: 'Add {amount} more to get {discount}.', promo_ready: '✓ You reached the minimum. Apply {code} and save.', language: 'Language'
    },
    el: {
      site: 'Ιστότοπος', title: 'Παράγγειλε και παρέλαβε από το ARGO', subtitle: 'Διάλεξε, προσάρμοσε και στείλε την παραγγελία σου απευθείας στο κατάστημα.',
      pickup: 'Μόνο παραλαβή από το κατάστημα', delivery: 'Για διανομή χρησιμοποίησε Deliveroo ή Just Eat από την αρχική σελίδα.', today_offer: 'ΣΗΜΕΡΙΝΗ ΠΡΟΣΦΟΡΑ · ΜΟΝΟ ΠΑΡΑΛΑΒΗ ARGO DIRECT', use_offer: 'ΧΡΗΣΙΜΟΠΟΙΗΣΕ ΤΗΝ ΠΡΟΣΦΟΡΑ',
      your_order: 'Η παραγγελία σου', empty_cart: 'Το καλάθι είναι άδειο', promo_code: 'Κωδικός έκπτωσης', apply: 'ΕΦΑΡΜΟΓΗ', subtotal: 'Μερικό σύνολο', discount: 'Έκπτωση', total: 'Σύνολο', continue: 'ΣΥΝΕΧΕΙΑ', all: 'Όλα',
      customize: 'ΠΡΟΣΑΡΜΟΓΗ +', add: '+ ΠΡΟΣΘΗΚΗ', unavailable_price: 'Η τιμή δεν είναι προσωρινά διαθέσιμη', customize_title: 'Προσαρμογή', item_note: 'Σημείωση για αυτό το προϊόν', item_note_example: 'π.χ. καλοψημένο, κομμένο στη μέση...',
      cancel: 'ΑΚΥΡΩΣΗ', add_item: 'ΠΡΟΣΘΗΚΗ', order_title: 'Ολοκλήρωση παραγγελίας', name: 'Όνομα *', phone: 'Τηλέφωνο *', email: 'Email', order_type: 'Τύπος παραγγελίας', pickup_value: 'Παραλαβή από το ARGO',
      payment: 'Πληρωμή', pay_pickup: 'Κατά την παραλαβή', desired_time: 'Ώρα παραλαβής', time_hint: 'Η πρώτη διαθέσιμη ώρα είναι σε 30 λεπτά.', order_notes: 'Σημειώσεις παραγγελίας', send_order: 'ΑΠΟΣΤΟΛΗ ΠΑΡΑΓΓΕΛΙΑΣ', sending: 'ΑΠΟΣΤΟΛΗ…', note: 'Σημείωση',
      required: 'Το όνομα και το τηλέφωνο είναι υποχρεωτικά.', time_error: 'Η παραλαβή πρέπει να είναι τουλάχιστον 30 λεπτά από τώρα.', promo_check: 'Έλεγξε τον κωδικό έκπτωσης πριν την αποστολή.', order_error: 'Η παραγγελία δεν στάλθηκε. Δοκίμασε ξανά ή τηλεφώνησέ μας.',
      promo_expired: 'Ο κωδικός έκπτωσης δεν ισχύει πλέον. Δοκίμασε ξανά.', received: 'παραλήφθηκε', wait_confirm: 'Περίμενε την επιβεβαίωση του καταστήματος.', too_many: 'Επιλέχθηκαν πάρα πολλές επιλογές.',
      emergency_alert: 'Το εφεδρικό μενού είναι μόνο για προβολή. Δοκίμασε ξανά σύντομα.', emergency_note: 'Εφεδρικό μενού μόνο για προβολή. Οι τιμές και οι παραγγελίες θα επανέλθουν μόλις αποκατασταθεί η υπηρεσία.',
      menu_unavailable: 'Το μενού δεν είναι προσωρινά διαθέσιμο.', retry_soon: 'Το μενού δεν είναι διαθέσιμο. Δοκίμασε ξανά σύντομα.', add_products: 'Πρόσθεσε πρώτα προϊόντα.', min_order: 'Ελάχιστη παραγγελία {amount} για αυτόν τον κωδικό.', wrong_day: 'Αυτός ο κωδικός δεν ισχύει σήμερα.',
      first_only: 'Το BENVENUTO ισχύει μόνο για την πρώτη απευθείας παραγγελία.', phone_first: 'Βάλε το τηλέφωνό σου για να χρησιμοποιήσεις το BENVENUTO.', max_uses: 'Ο κωδικός έφτασε το όριο χρήσεων.', used_offer: 'Έχεις ήδη χρησιμοποιήσει αυτή την προσφορά.', invalid_code: 'Μη έγκυρος ή ληγμένος κωδικός.',
      savings: 'κερδίζεις {amount}', promo_main: '{discount} στην παραλαβή από το ARGO', promo_meta: 'Ελάχιστη παραγγελία {amount}. Η προσφορά ισχύει μόνο στο ARGO Direct, όχι σε Deliveroo ή Just Eat.',
      promo_start: 'Πρόσθεσε προϊόντα μέχρι {amount} για τον κωδικό {code}.', promo_left: 'Χρειάζονται ακόμη {amount} για έκπτωση {discount}.', promo_ready: '✓ Έφτασες το όριο. Εφάρμοσε το {code} και κέρδισε.', language: 'Γλώσσα'
    },
    es: {
      site: 'Sitio web', title: 'Pide y recoge en ARGO', subtitle: 'Elige, personaliza y envía tu pedido directamente al restaurante.', pickup: 'Solo recogida en el local', delivery: 'Para entrega a domicilio, usa Deliveroo o Just Eat desde la página principal.',
      today_offer: 'OFERTA DE HOY · SOLO RECOGIDA ARGO DIRECT', use_offer: 'USAR ESTA OFERTA', your_order: 'Tu pedido', empty_cart: 'Tu cesta está vacía', promo_code: 'Código de descuento', apply: 'APLICAR', subtotal: 'Subtotal', discount: 'Descuento', total: 'Total', continue: 'CONTINUAR', all: 'Todo',
      customize: 'PERSONALIZAR +', add: '+ AÑADIR', unavailable_price: 'Precio no disponible temporalmente', customize_title: 'Personalizar', item_note: 'Nota para este artículo', item_note_example: 'Ej. bien hecho, cortado por la mitad...', cancel: 'CANCELAR', add_item: 'AÑADIR',
      order_title: 'Completa tu pedido', name: 'Nombre *', phone: 'Teléfono *', email: 'Email', order_type: 'Tipo de pedido', pickup_value: 'Recogida en ARGO', payment: 'Pago', pay_pickup: 'Al recoger', desired_time: 'Hora deseada', time_hint: 'La primera hora disponible es dentro de 30 minutos.', order_notes: 'Notas del pedido', send_order: 'ENVIAR PEDIDO', sending: 'ENVIANDO…', note: 'Nota',
      required: 'El nombre y el teléfono son obligatorios.', time_error: 'La recogida debe ser al menos dentro de 30 minutos.', promo_check: 'Comprueba el código de descuento antes de enviar.', order_error: 'No se pudo enviar el pedido. Inténtalo de nuevo o llámanos.', promo_expired: 'El código ya no es válido. Inténtalo de nuevo.', received: 'recibido', wait_confirm: 'Espera la confirmación del restaurante.', too_many: 'Has seleccionado demasiadas opciones.',
      emergency_alert: 'El menú de emergencia es solo de consulta. Inténtalo de nuevo en breve.', emergency_note: 'Menú de emergencia solo de consulta. Los precios y pedidos volverán cuando se restablezca el servicio.', menu_unavailable: 'Menú no disponible temporalmente.', retry_soon: 'Menú no disponible. Inténtalo de nuevo en breve.', add_products: 'Añade productos primero.', min_order: 'Pedido mínimo {amount} para este código.', wrong_day: 'Este código no es válido hoy.', first_only: 'BENVENUTO es solo para el primer pedido directo.', phone_first: 'Introduce tu teléfono para usar BENVENUTO.', max_uses: 'Este código ha alcanzado el límite de usos.', used_offer: 'Ya has usado esta oferta.', invalid_code: 'Código no válido o caducado.',
      savings: 'ahorras {amount}', promo_main: '{discount} en pedidos para recoger en ARGO', promo_meta: 'Pedido mínimo {amount}. Oferta válida solo en ARGO Direct, no en Deliveroo ni Just Eat.', promo_start: 'Añade productos hasta {amount} para usar el código {code}.', promo_left: 'Te faltan {amount} para obtener {discount}.', promo_ready: '✓ Has alcanzado el mínimo. Aplica {code} y ahorra.', language: 'Idioma'
    },
    de: {
      site: 'Website', title: 'Bei ARGO bestellen und abholen', subtitle: 'Auswählen, anpassen und direkt beim Restaurant bestellen.', pickup: 'Nur Abholung im Restaurant', delivery: 'Für Lieferung nutze Deliveroo oder Just Eat auf der Hauptseite.', today_offer: 'HEUTIGES ANGEBOT · NUR ARGO DIRECT ABHOLUNG', use_offer: 'ANGEBOT NUTZEN',
      your_order: 'Deine Bestellung', empty_cart: 'Dein Warenkorb ist leer', promo_code: 'Rabattcode', apply: 'ANWENDEN', subtotal: 'Zwischensumme', discount: 'Rabatt', total: 'Gesamt', continue: 'WEITER', all: 'Alle', customize: 'ANPASSEN +', add: '+ HINZUFÜGEN', unavailable_price: 'Preis vorübergehend nicht verfügbar', customize_title: 'Anpassen', item_note: 'Hinweis zu diesem Artikel', item_note_example: 'Z. B. gut durch, halbiert...', cancel: 'ABBRECHEN', add_item: 'HINZUFÜGEN',
      order_title: 'Bestellung abschließen', name: 'Name *', phone: 'Telefon *', email: 'E-Mail', order_type: 'Bestellart', pickup_value: 'Abholung bei ARGO', payment: 'Zahlung', pay_pickup: 'Bei Abholung', desired_time: 'Gewünschte Zeit', time_hint: 'Die erste verfügbare Zeit ist in 30 Minuten.', order_notes: 'Hinweise zur Bestellung', send_order: 'BESTELLUNG SENDEN', sending: 'WIRD GESENDET…', note: 'Hinweis',
      required: 'Name und Telefonnummer sind erforderlich.', time_error: 'Die Abholung muss mindestens 30 Minuten ab jetzt erfolgen.', promo_check: 'Prüfe den Rabattcode vor dem Absenden.', order_error: 'Bestellung konnte nicht gesendet werden. Versuche es erneut oder ruf uns an.', promo_expired: 'Der Rabattcode ist nicht mehr gültig. Versuche es erneut.', received: 'eingegangen', wait_confirm: 'Bitte warte auf die Bestätigung des Restaurants.', too_many: 'Zu viele Optionen ausgewählt.',
      emergency_alert: 'Das Notfallmenü dient nur zur Ansicht. Versuche es später erneut.', emergency_note: 'Notfallmenü nur zur Ansicht. Preise und Bestellungen sind wieder verfügbar, sobald der Live-Service läuft.', menu_unavailable: 'Menü vorübergehend nicht verfügbar.', retry_soon: 'Menü nicht verfügbar. Bitte versuche es später erneut.', add_products: 'Füge zuerst Produkte hinzu.', min_order: 'Mindestbestellwert {amount} für diesen Code.', wrong_day: 'Dieser Code ist heute nicht gültig.', first_only: 'BENVENUTO gilt nur für die erste Direktbestellung.', phone_first: 'Gib deine Telefonnummer ein, um BENVENUTO zu nutzen.', max_uses: 'Dieser Code hat sein Nutzungslimit erreicht.', used_offer: 'Du hast dieses Angebot bereits genutzt.', invalid_code: 'Ungültiger oder abgelaufener Code.',
      savings: 'du sparst {amount}', promo_main: '{discount} auf Abholbestellungen bei ARGO', promo_meta: 'Mindestbestellwert {amount}. Das Angebot gilt nur bei ARGO Direct, nicht bei Deliveroo oder Just Eat.', promo_start: 'Füge Produkte bis {amount} hinzu, um Code {code} zu nutzen.', promo_left: 'Noch {amount} bis zu {discount}.', promo_ready: '✓ Mindestwert erreicht. {code} anwenden und sparen.', language: 'Sprache'
    },
    fr: {
      site: 'Site web', title: 'Commandez et retirez chez ARGO', subtitle: 'Choisissez, personnalisez et envoyez votre commande directement au restaurant.', pickup: 'Retrait au restaurant uniquement', delivery: "Pour la livraison, utilisez Deliveroo ou Just Eat depuis la page d'accueil.", today_offer: "OFFRE DU JOUR · RETRAIT ARGO DIRECT UNIQUEMENT", use_offer: 'UTILISER CETTE OFFRE',
      your_order: 'Votre commande', empty_cart: 'Votre panier est vide', promo_code: 'Code promo', apply: 'APPLIQUER', subtotal: 'Sous-total', discount: 'Réduction', total: 'Total', continue: 'CONTINUER', all: 'Tout', customize: 'PERSONNALISER +', add: '+ AJOUTER', unavailable_price: 'Prix temporairement indisponible', customize_title: 'Personnaliser', item_note: 'Note pour cet article', item_note_example: 'Ex. bien cuit, coupé en deux...', cancel: 'ANNULER', add_item: 'AJOUTER',
      order_title: 'Finalisez votre commande', name: 'Nom *', phone: 'Téléphone *', email: 'E-mail', order_type: 'Type de commande', pickup_value: 'Retrait chez ARGO', payment: 'Paiement', pay_pickup: 'Au retrait', desired_time: 'Heure souhaitée', time_hint: 'Le premier créneau disponible est dans 30 minutes.', order_notes: 'Notes de commande', send_order: 'ENVOYER LA COMMANDE', sending: 'ENVOI…', note: 'Note',
      required: 'Le nom et le téléphone sont obligatoires.', time_error: "Le retrait doit être prévu dans au moins 30 minutes.", promo_check: "Vérifiez le code promo avant l'envoi.", order_error: "Impossible d'envoyer la commande. Réessayez ou appelez-nous.", promo_expired: "Le code promo n'est plus valable. Réessayez.", received: 'reçue', wait_confirm: 'Attendez la confirmation du restaurant.', too_many: "Trop d'options sélectionnées.",
      emergency_alert: "Le menu de secours est en consultation uniquement. Réessayez bientôt.", emergency_note: 'Menu de secours en consultation uniquement. Les prix et commandes reviendront dès le rétablissement du service.', menu_unavailable: 'Menu temporairement indisponible.', retry_soon: 'Menu indisponible. Réessayez bientôt.', add_products: "Ajoutez d'abord des produits.", min_order: 'Commande minimum de {amount} pour ce code.', wrong_day: "Ce code n'est pas valable aujourd'hui.", first_only: 'BENVENUTO est réservé à la première commande directe.', phone_first: 'Saisissez votre téléphone pour utiliser BENVENUTO.', max_uses: "Ce code a atteint sa limite d'utilisation.", used_offer: 'Vous avez déjà utilisé cette offre.', invalid_code: 'Code invalide ou expiré.',
      savings: 'vous économisez {amount}', promo_main: '{discount} sur les commandes à retirer chez ARGO', promo_meta: "Commande minimum {amount}. Offre valable uniquement sur ARGO Direct, pas sur Deliveroo ni Just Eat.", promo_start: "Ajoutez des produits jusqu'à {amount} pour utiliser le code {code}.", promo_left: 'Il vous manque {amount} pour obtenir {discount}.', promo_ready: '✓ Minimum atteint. Appliquez {code} et économisez.', language: 'Langue'
    }
  };

  const categoryRows = [
    ['Pita','Pita','Πίτες','Pitas','Pita','Pitas'], ['Piatti','Plates','Πιάτα','Platos','Tellergerichte','Plats'], ['Mezedes','Meze','Μεζέδες','Meze','Meze','Mezzés'],
    ['Insalate','Salads','Σαλάτες','Ensaladas','Salate','Salades'], ['Vegetariano','Vegetarian','Χορτοφαγικά','Vegetariano','Vegetarisch','Végétarien'], ['Salse','Sauces','Σάλτσες','Salsas','Saucen','Sauces'],
    ['Dolci','Desserts','Γλυκά','Postres','Desserts','Desserts'], ['Bevande','Drinks','Αναψυκτικά','Bebidas','Getränke','Boissons'], ['Birre','Beers','Μπίρες','Cervezas','Biere','Bières'],
    ['Vini','Wines','Κρασιά','Vinos','Weine','Vins'], ['Posate','Cutlery','Μαχαιροπίρουνα','Cubiertos','Besteck','Couverts']
  ];
  const nameRows = [
    ['Mix Grill','Mixed grill','Ποικιλία σχάρας','Parrillada mixta','Grillteller','Grillades mixtes'], ['Insalata greca choriatiki','Greek salad (choriatiki)','Χωριάτικη σαλάτα','Ensalada griega choriatiki','Griechischer Bauernsalat','Salade grecque choriatiki'],
    ['Gyros di Suino al Piatto','Pork gyros plate','Γύρος χοιρινός μερίδα','Plato de gyros de cerdo','Schweinegyros-Teller','Assiette de gyros de porc'], ['Pita Gyros','Pork gyros pita','Πίτα γύρος χοιρινός','Pita gyros de cerdo','Pita mit Schweinegyros','Pita gyros de porc'],
    ['Set posate x1','Cutlery set x1','Σετ μαχαιροπίρουνα x1','Cubiertos x1','Besteckset x1','Couverts x1'], ['Tirokeftedes pikantikoi','Spicy cheese croquettes','Πικάντικοι τυροκεφτέδες','Croquetas picantes de queso','Pikante Käsebällchen','Croquettes de fromage épicées'],
    ['Insalata verde con pomodorini','Green salad with cherry tomatoes','Πράσινη σαλάτα με ντοματίνια','Ensalada verde con tomates cherry','Grüner Salat mit Kirschtomaten','Salade verte aux tomates cerises'],
    ['Feta in pastafillo con miele e sesamo','Feta in filo pastry with honey and sesame','Φέτα σε φύλλο με μέλι και σουσάμι','Feta en pasta filo con miel y sésamo','Feta im Filoteig mit Honig und Sesam','Feta en pâte filo, miel et sésame'],
    ['Gyros di Pollo al Piatto','Chicken gyros plate','Γύρος κοτόπουλο μερίδα','Plato de gyros de pollo','Hähnchengyros-Teller','Assiette de gyros de poulet'], ['Pita Pollo','Chicken pita','Πίτα κοτόπουλο','Pita de pollo','Hähnchen-Pita','Pita au poulet'],
    ['Bifteki alla griglia','Grilled bifteki','Μπιφτέκι σχάρας','Bifteki a la parrilla','Gegrilltes Bifteki','Bifteki grillé'], ['Aris grande','Large Aris sauce','Σάλτσα Άρης μεγάλη','Salsa Aris grande','Aris-Sauce groß','Sauce Aris grande'],
    ['Pita vegan','Vegan pita','Vegan πίτα','Pita vegana','Vegane Pita','Pita végane'], ['Piatto Souvlaki Kotopoulo','Chicken souvlaki plate','Σουβλάκι κοτόπουλο μερίδα','Plato de souvlaki de pollo','Hähnchen-Souvlaki-Teller','Assiette de souvlaki de poulet'],
    ['Pita Agnello','Lamb pita','Πίτα αρνί','Pita de cordero','Lamm-Pita','Pita à l’agneau'], ['Halloumi alla griglia','Grilled halloumi','Χαλούμι σχάρας','Halloumi a la parrilla','Gegrillter Halloumi','Halloumi grillé'],
    ['Pita dolmas','Dolmas pita','Πίτα ντολμαδάκια','Pita de dolmas','Dolmas-Pita','Pita aux dolmas'], ['Kleoni Bianco 375ml','Kleoni white 375ml','Kleoni λευκό 375ml','Kleoni blanco 375ml','Kleoni Weiß 375ml','Kleoni blanc 375ml'],
    ['Spiedino di suino con pita e salsa','Pork skewer with pita and sauce','Χοιρινό καλαμάκι με πίτα και σάλτσα','Brocheta de cerdo con pita y salsa','Schweinespieß mit Pita und Sauce','Brochette de porc, pita et sauce'],
    ['Piatto Souvlaki Chirino','Pork souvlaki plate','Σουβλάκι χοιρινό μερίδα','Plato de souvlaki de cerdo','Schweine-Souvlaki-Teller','Assiette de souvlaki de porc'],
    ['Salsa curry grande','Large curry sauce','Σάλτσα κάρυ μεγάλη','Salsa curry grande','Currysauce groß','Sauce curry grande'], ['Spiedino di pollo con pita e salsa','Chicken skewer with pita and sauce','Καλαμάκι κοτόπουλο με πίτα και σάλτσα','Brocheta de pollo con pita y salsa','Hähnchenspieß mit Pita und Sauce','Brochette de poulet, pita et sauce'],
    ['Pita Salsiccia','Greek sausage pita','Πίτα λουκάνικο','Pita de salchicha griega','Pita mit griechischer Wurst','Pita à la saucisse grecque'], ['Kleoni Rosso 375ml','Kleoni red 375ml','Kleoni κόκκινο 375ml','Kleoni tinto 375ml','Kleoni Rot 375ml','Kleoni rouge 375ml'],
    ['Feta ed Olive','Feta and olives','Φέτα και ελιές','Feta y aceitunas','Feta und Oliven','Feta et olives'], ['Feta al Cartoccio','Baked feta parcel','Φέτα στο αλουμινόχαρτο','Feta al papillote','Feta aus der Folie','Feta en papillote'],
    ['Pita greca','Greek pita bread','Ελληνική πίτα','Pan de pita griego','Griechisches Pitabrot','Pain pita grec'], ['Yogurt greco al naturale grande','Large plain Greek yoghurt','Γιαούρτι σκέτο μεγάλο','Yogur griego natural grande','Griechischer Naturjoghurt groß','Yaourt grec nature grand'],
    ['Piatto Meze Vegetariano','Vegetarian meze plate','Χορτοφαγική ποικιλία μεζέδων','Plato de meze vegetariano','Vegetarischer Meze-Teller','Assiette de mezzés végétariens'], ['Yogurt con miele','Greek yoghurt with honey','Γιαούρτι με μέλι','Yogur griego con miel','Griechischer Joghurt mit Honig','Yaourt grec au miel'],
    ['Bistecche di suino con patatine fritte','Pork steaks with fries','Χοιρινές μπριζόλες με πατάτες','Filetes de cerdo con patatas fritas','Schweinesteaks mit Pommes','Steaks de porc avec frites'], ['Tzatziki piccola','Small tzatziki','Τζατζίκι μικρό','Tzatziki pequeño','Tzatziki klein','Petit tzatziki'],
    ['Pita Vegetariana','Vegetarian pita','Χορτοφαγική πίτα','Pita vegetariana','Vegetarische Pita','Pita végétarienne'], ['Acqua naturale 50cl','Still water 50cl','Νερό 50cl','Agua sin gas 50cl','Stilles Wasser 50cl','Eau plate 50cl'],
    ['Yogurt con Miele e Noci','Greek yoghurt with honey and walnuts','Γιαούρτι με μέλι και καρύδια','Yogur griego con miel y nueces','Griechischer Joghurt mit Honig und Walnüssen','Yaourt grec au miel et aux noix'],
    ['Pita chicky','Chicky chicken pita','Πίτα chicky με κοτόπουλο','Pita chicky de pollo','Chicky Hähnchen-Pita','Pita chicky au poulet'], ['Pita piggy','Piggy pork pita','Πίτα piggy με χοιρινό','Pita piggy de cerdo','Piggy Schweine-Pita','Pita piggy au porc'],
    ['Tirokafteri piccola','Small tirokafteri','Τυροκαυτερή μικρή','Tirokafteri pequeña','Tirokafteri klein','Petite tirokafteri'], ['Aris piccola','Small Aris sauce','Σάλτσα Άρης μικρή','Salsa Aris pequeña','Aris-Sauce klein','Petite sauce Aris'],
    ['Hummus piccola','Small hummus','Χούμους μικρό','Hummus pequeño','Hummus klein','Petit houmous'], ['Acqua frizzante 50cl','Sparkling water 50cl','Ανθρακούχο νερό 50cl','Agua con gas 50cl','Mineralwasser mit Kohlensäure 50cl','Eau gazeuse 50cl'],
    ['Polpettine di Melanzane','Aubergine croquettes','Μελιτζανοκεφτέδες','Croquetas de berenjena','Auberginenbällchen','Croquettes d’aubergine'], ['Polpettine di Ceci','Chickpea croquettes','Ρεβιθοκεφτέδες','Croquetas de garbanzos','Kichererbsenbällchen','Croquettes de pois chiches'],
    ['Filettini di Pollo Panati','Breaded chicken strips','Παναρισμένες λωρίδες κοτόπουλου','Tiras de pollo empanadas','Panierte Hähnchenstreifen','Aiguillettes de poulet panées'], ['Pita Vuota','Plain pita bread','Σκέτη πίτα','Pan de pita solo','Pitabrot pur','Pain pita nature'],
    ['Melitzanosalata piccola','Small melitzanosalata','Μελιτζανοσαλάτα μικρή','Melitzanosalata pequeña','Melitzanosalata klein','Petite melitzanosalata'], ['Polpettine di melanzane e formaggio','Aubergine and cheese croquettes','Μελιτζανοκεφτέδες με τυρί','Croquetas de berenjena y queso','Auberginen-Käse-Bällchen','Croquettes d’aubergine et fromage'],
    ['Salsa al curry piccola','Small curry sauce','Σάλτσα κάρυ μικρή','Salsa curry pequeña','Currysauce klein','Petite sauce curry'], ['Yogurt greco naturale piccola','Small plain Greek yoghurt','Γιαούρτι σκέτο μικρό','Yogur griego natural pequeño','Griechischer Naturjoghurt klein','Petit yaourt grec nature'],
    ['Patatine fritte','French fries','Τηγανητές πατάτες','Patatas fritas','Pommes frites','Frites'], ['Maionese','Mayonnaise','Μαγιονέζα','Mayonesa','Mayonnaise','Mayonnaise'],
    ['Ichnusa non filtrata 50cl','Ichnusa unfiltered 50cl','Ichnusa αφιλτράριστη 50cl','Ichnusa sin filtrar 50cl','Ichnusa ungefiltert 50cl','Ichnusa non filtrée 50cl']
  ];

  const descRows = [
    ['Gyros di suino, filetto di pollo, salsiccia greca, bifteki di manzo e agnello — servito con pita greca e tzatziki','Pork gyros, chicken fillet, Greek sausage and beef-and-lamb bifteki — served with Greek pita and tzatziki','Γύρος χοιρινός, φιλέτο κοτόπουλο, ελληνικό λουκάνικο και μπιφτέκι μοσχάρι-αρνί — με πίτα και τζατζίκι','Gyros de cerdo, filete de pollo, salchicha griega y bifteki de ternera y cordero — con pita y tzatziki','Schweinegyros, Hähnchenfilet, griechische Wurst und Rind-Lamm-Bifteki — mit Pita und Tzatziki','Gyros de porc, filet de poulet, saucisse grecque et bifteki bœuf-agneau — avec pita et tzatziki'],
    ['Pomodori, peperone, cetrioli, olive di Kalamata, cipolla, feta DOP e origano con olio extravergine','Tomatoes, pepper, cucumber, Kalamata olives, onion, PDO feta and oregano with extra virgin olive oil','Ντομάτα, πιπεριά, αγγούρι, ελιές Καλαμών, κρεμμύδι, φέτα ΠΟΠ, ρίγανη και εξαιρετικό παρθένο ελαιόλαδο','Tomate, pimiento, pepino, aceitunas Kalamata, cebolla, feta DOP, orégano y aceite de oliva virgen extra','Tomaten, Paprika, Gurke, Kalamata-Oliven, Zwiebel, Feta g.U., Oregano und natives Olivenöl extra','Tomates, poivron, concombre, olives de Kalamata, oignon, feta AOP, origan et huile d’olive vierge extra'],
    ['Salsa con yogurt greco, cetriolo e aglio, fatta ogni giorno','Greek yoghurt sauce with cucumber and garlic, made fresh daily','Σάλτσα με ελληνικό γιαούρτι, αγγούρι και σκόρδο, φρέσκια κάθε μέρα','Salsa de yogur griego, pepino y ajo, hecha cada día','Sauce aus griechischem Joghurt, Gurke und Knoblauch, täglich frisch','Sauce au yaourt grec, concombre et ail, préparée chaque jour'],
    ['Pita artigianale farcita con formaggio Feta DOP, patate fritte, pomodoro fresco, insalata, cipolla di Tropea e salsa a scelta','Handmade pita with PDO feta, fries, fresh tomato, salad, Tropea onion and your choice of sauce','Χειροποίητη πίτα με φέτα ΠΟΠ, πατάτες, φρέσκια ντομάτα, σαλάτα, κρεμμύδι Tropea και σάλτσα επιλογής','Pita artesanal con feta DOP, patatas fritas, tomate fresco, ensalada, cebolla de Tropea y salsa a elegir','Handgemachte Pita mit Feta g.U., Pommes, frischer Tomate, Salat, Tropea-Zwiebel und Sauce nach Wahl','Pita artisanale avec feta AOP, frites, tomate fraîche, salade, oignon de Tropea et sauce au choix'],
    ['Formaggio greco caldo, croccante fuori e filante dentro.','Hot Greek cheese, crisp outside and melted inside.','Ζεστό ελληνικό τυρί, τραγανό έξω και λιωμένο μέσα.','Queso griego caliente, crujiente por fuera y fundido por dentro.','Heißer griechischer Käse, außen knusprig und innen zartschmelzend.','Fromage grec chaud, croustillant dehors et fondant dedans.'],
    ['Dolce greco con pasta fillo, frutta secca e sciroppo.','Greek filo pastry dessert with nuts and syrup.','Ελληνικό γλυκό με φύλλο, ξηρούς καρπούς και σιρόπι.','Postre griego de pasta filo, frutos secos y almíbar.','Griechisches Filoteiggebäck mit Nüssen und Sirup.','Dessert grec à la pâte filo, fruits secs et sirop.'],
    ['Gyros di suino servito come piatto completo.','Pork gyros served as a complete plate.','Γύρος χοιρινός σε πλήρη μερίδα.','Gyros de cerdo servido como plato completo.','Schweinegyros als vollständiger Teller.','Gyros de porc servi en assiette complète.'], ['Pita greca con gyros di suino e accompagnamenti.','Greek pita with pork gyros and fillings.','Ελληνική πίτα με γύρο χοιρινό και συνοδευτικά.','Pita griega con gyros de cerdo y acompañamientos.','Griechische Pita mit Schweinegyros und Beilagen.','Pita grecque avec gyros de porc et garnitures.'],
    ['Polpettine piccanti al formaggio, 6 pezzi','Spicy cheese croquettes, 6 pieces','Πικάντικοι τυροκεφτέδες, 6 τεμάχια','Croquetas picantes de queso, 6 unidades','Pikante Käsebällchen, 6 Stück','Croquettes de fromage épicées, 6 pièces'], ['Salsa con Feta e peperoncino, piccante e cremosa','Creamy spicy feta and chilli sauce','Κρεμώδης πικάντικη σάλτσα με φέτα και πιπεριά','Salsa cremosa y picante de feta y chile','Cremige, pikante Feta-Chili-Sauce','Sauce crémeuse et épicée à la feta et au piment'],
    ['Insalata verde con pomodorini','Green salad with cherry tomatoes','Πράσινη σαλάτα με ντοματίνια','Ensalada verde con tomates cherry','Grüner Salat mit Kirschtomaten','Salade verte aux tomates cerises'], ['Feta avvolta in pasta fillo con miele e sesamo','Feta wrapped in filo pastry with honey and sesame','Φέτα τυλιγμένη σε φύλλο με μέλι και σουσάμι','Feta envuelta en pasta filo con miel y sésamo','Feta im Filoteig mit Honig und Sesam','Feta enveloppée de pâte filo avec miel et sésame'],
    ['Feta greca, semplice e saporita.','Simple, flavourful Greek feta.','Ελληνική φέτα, απλή και νόστιμη.','Feta griega, sencilla y sabrosa.','Griechischer Feta, pur und würzig.','Feta grecque, simple et savoureuse.'], ['Gyros di pollo servito come piatto completo.','Chicken gyros served as a complete plate.','Γύρος κοτόπουλο σε πλήρη μερίδα.','Gyros de pollo servido como plato completo.','Hähnchengyros als vollständiger Teller.','Gyros de poulet servi en assiette complète.'],
    ['Dolce tradizionale greco con pasta kataifi e sciroppo.','Traditional Greek kataifi pastry with syrup.','Παραδοσιακό ελληνικό κανταΐφι με σιρόπι.','Postre griego tradicional de pasta kataifi y almíbar.','Traditionelles griechisches Kataifi-Gebäck mit Sirup.','Dessert grec traditionnel aux cheveux d’ange kataifi et sirop.'], ['Pita greca con pollo e accompagnamenti.','Greek pita with chicken and fillings.','Ελληνική πίτα με κοτόπουλο και συνοδευτικά.','Pita griega con pollo y acompañamientos.','Griechische Pita mit Hähnchen und Beilagen.','Pita grecque au poulet et garnitures.'],
    ['Bifteki alla griglia con contorno','Grilled bifteki with side dish','Μπιφτέκι σχάρας με συνοδευτικό','Bifteki a la parrilla con guarnición','Gegrilltes Bifteki mit Beilage','Bifteki grillé avec accompagnement'], ['4 involtini di foglie di vite, serviti con tzatziki','4 stuffed vine leaves, served with tzatziki','4 ντολμαδάκια, σερβίρονται με τζατζίκι','4 hojas de parra rellenas, servidas con tzatziki','4 gefüllte Weinblätter, serviert mit Tzatziki','4 feuilles de vigne farcies, servies avec tzatziki'],
    ['Pita vegan con farcitura vegetale','Vegan pita with plant-based filling','Vegan πίτα με φυτική γέμιση','Pita vegana con relleno vegetal','Vegane Pita mit pflanzlicher Füllung','Pita végane à la garniture végétale'], ['Souvlaki di pollo in versione piatto completo.','Chicken souvlaki served as a complete plate.','Σουβλάκι κοτόπουλο σε πλήρη μερίδα.','Souvlaki de pollo servido como plato completo.','Hähnchen-Souvlaki als vollständiger Teller.','Souvlaki de poulet servi en assiette complète.'],
    ['Pita con agnello dal gusto deciso.','Pita with richly flavoured lamb.','Πίτα με αρνί και γεμάτη γεύση.','Pita con cordero de sabor intenso.','Pita mit kräftig gewürztem Lamm.','Pita à l’agneau au goût relevé.'], ['Formaggio cipriota di latte di pecora e capra, grigliato — croccante fuori, morbido dentro','Grilled Cypriot sheep’s and goat’s milk cheese — crisp outside, soft inside','Κυπριακό τυρί από πρόβειο και κατσικίσιο γάλα, ψητό — τραγανό έξω, μαλακό μέσα','Queso chipriota de leche de oveja y cabra a la parrilla — crujiente fuera y tierno dentro','Gegrillter zypriotischer Schaf- und Ziegenkäse — außen knusprig, innen weich','Fromage chypriote de brebis et chèvre grillé — croustillant dehors, tendre dedans'],
    ['Pita con dolmas e farcitura vegetariana','Pita with dolmas and vegetarian filling','Πίτα με ντολμαδάκια και χορτοφαγική γέμιση','Pita con dolmas y relleno vegetariano','Pita mit Dolmas und vegetarischer Füllung','Pita aux dolmas et garniture végétarienne'], ['Salsa a base di ceci e tahini','Chickpea and tahini dip','Σάλτσα από ρεβίθια και ταχίνι','Salsa de garbanzos y tahini','Dip aus Kichererbsen und Tahini','Sauce de pois chiches et tahini'],
    ['Torta tradizionale greca all\'arancia con pasta fillo, arancia fresca e vaniglia','Traditional Greek orange cake with filo pastry, fresh orange and vanilla','Παραδοσιακή ελληνική πορτοκαλόπιτα με φύλλο, φρέσκο πορτοκάλι και βανίλια','Pastel griego tradicional de naranja con pasta filo, naranja fresca y vainilla','Traditioneller griechischer Orangenkuchen mit Filoteig, frischer Orange und Vanille','Gâteau grec traditionnel à l’orange, pâte filo, orange fraîche et vanille'],
    ['Spiedino di suino con pita greca e salsa','Pork skewer with Greek pita and sauce','Χοιρινό καλαμάκι με ελληνική πίτα και σάλτσα','Brocheta de cerdo con pita griega y salsa','Schweinespieß mit griechischer Pita und Sauce','Brochette de porc avec pita grecque et sauce'], ['3 spiedini di suino con patate fritte, pomodoro, cipolla di Tropea, insalata, tzatziki e pita','3 pork skewers with fries, tomato, Tropea onion, salad, tzatziki and pita','3 χοιρινά καλαμάκια με πατάτες, ντομάτα, κρεμμύδι Tropea, σαλάτα, τζατζίκι και πίτα','3 brochetas de cerdo con patatas fritas, tomate, cebolla de Tropea, ensalada, tzatziki y pita','3 Schweinespieße mit Pommes, Tomate, Tropea-Zwiebel, Salat, Tzatziki und Pita','3 brochettes de porc avec frites, tomate, oignon de Tropea, salade, tzatziki et pita'],
    ['Pita artigianale con polpette di macinato di agnello e manzo, patate fritte, pomodoro fresco, insalata, cipolla di Tropea e salsa a scelta','Handmade pita with lamb-and-beef patties, fries, fresh tomato, salad, Tropea onion and your choice of sauce','Χειροποίητη πίτα με μπιφτέκι αρνιού και μοσχαριού, πατάτες, φρέσκια ντομάτα, σαλάτα, κρεμμύδι Tropea και σάλτσα επιλογής','Pita artesanal con hamburguesas de cordero y ternera, patatas, tomate, ensalada, cebolla de Tropea y salsa a elegir','Handgemachte Pita mit Lamm-Rind-Hackbällchen, Pommes, Tomate, Salat, Tropea-Zwiebel und Sauce nach Wahl','Pita artisanale avec boulettes d’agneau et bœuf, frites, tomate, salade, oignon de Tropea et sauce au choix'],
    ['Spiedino di pollo con pita greca e salsa','Chicken skewer with Greek pita and sauce','Καλαμάκι κοτόπουλο με ελληνική πίτα και σάλτσα','Brocheta de pollo con pita griega y salsa','Hähnchenspieß mit griechischer Pita und Sauce','Brochette de poulet avec pita grecque et sauce'], ['Pita con salsiccia greca.','Pita with Greek sausage.','Πίτα με ελληνικό λουκάνικο.','Pita con salchicha griega.','Pita mit griechischer Wurst.','Pita à la saucisse grecque.'],
    ['Torta al cioccolato greca — densa, umida e irresistibile','Greek chocolate cake — rich, moist and irresistible','Ελληνική σοκολατόπιτα — πλούσια, ζουμερή και ακαταμάχητη','Pastel griego de chocolate — intenso, jugoso e irresistible','Griechischer Schokoladenkuchen — saftig und unwiderstehlich','Gâteau grec au chocolat — riche, moelleux et irrésistible'], ['Feta DOP con olive di Kalamata','PDO feta with Kalamata olives','Φέτα ΠΟΠ με ελιές Καλαμών','Feta DOP con aceitunas Kalamata','Feta g.U. mit Kalamata-Oliven','Feta AOP aux olives de Kalamata'],
    ['Salsa a base di melanzane, ricetta tradizionale greca','Aubergine dip, traditional Greek recipe','Μελιτζανοσαλάτα, παραδοσιακή ελληνική συνταγή','Salsa de berenjena, receta griega tradicional','Auberginen-Dip nach traditionellem griechischem Rezept','Caviar d’aubergine, recette grecque traditionnelle'], ['Formaggio Feta DOP con cipolla e pomodoro, cotto al cartoccio','PDO feta with onion and tomato, baked in foil','Φέτα ΠΟΠ με κρεμμύδι και ντομάτα, ψημένη σε αλουμινόχαρτο','Feta DOP con cebolla y tomate, horneada al papillote','Feta g.U. mit Zwiebel und Tomate, in Folie gebacken','Feta AOP avec oignon et tomate, cuite en papillote'],
    ['Pita greca artigianale','Handmade Greek pita bread','Χειροποίητη ελληνική πίτα','Pan de pita griego artesanal','Handgemachtes griechisches Pitabrot','Pain pita grec artisanal'], ['Selezione vegetariana ARGO al piatto','ARGO vegetarian selection served as a plate','Χορτοφαγική ποικιλία ARGO σε πιάτο','Selección vegetariana ARGO en plato','Vegetarische ARGO-Auswahl als Teller','Sélection végétarienne ARGO en assiette'],
    ['Patate, melanzane, ragù, besciamella e formaggio a strati, cotto al forno, servito con insalata, pita e tzatziki','Layers of potato, aubergine, meat sauce, béchamel and cheese, oven-baked and served with salad, pita and tzatziki','Στρώσεις πατάτας, μελιτζάνας, κιμά, μπεσαμέλ και τυριού, ψημένες στον φούρνο, με σαλάτα, πίτα και τζατζίκι','Capas de patata, berenjena, ragú, bechamel y queso al horno, con ensalada, pita y tzatziki','Schichten aus Kartoffeln, Auberginen, Hackfleischsauce, Béchamel und Käse, mit Salat, Pita und Tzatziki','Pommes de terre, aubergines, sauce à la viande, béchamel et fromage en couches, avec salade, pita et tzatziki'],
    ['Pomodoro, Feta e peperoncino in terracotta — accompagnato da 1 pita vuota','Tomato, feta and chilli baked in terracotta — served with 1 plain pita','Ντομάτα, φέτα και πιπεριά σε πήλινο — συνοδεύεται με 1 σκέτη πίτα','Tomate, feta y chile en cazuela de barro — con 1 pita sola','Tomate, Feta und Chili im Tontopf — mit 1 Pitabrot','Tomate, feta et piment en terre cuite — avec 1 pita nature'],
    ['4 polpettine di melanzane fritte, servite con tzatziki','4 fried aubergine croquettes, served with tzatziki','4 τηγανητοί μελιτζανοκεφτέδες, με τζατζίκι','4 croquetas de berenjena fritas, con tzatziki','4 frittierte Auberginenbällchen mit Tzatziki','4 croquettes d’aubergine frites avec tzatziki'], ['4 polpettine di ceci fritte, servite con tzatziki','4 fried chickpea croquettes, served with tzatziki','4 τηγανητοί ρεβιθοκεφτέδες, με τζατζίκι','4 croquetas de garbanzos fritas, con tzatziki','4 frittierte Kichererbsenbällchen mit Tzatziki','4 croquettes de pois chiches frites avec tzatziki'],
    ['Filettini di pollo panati','Breaded chicken strips','Παναρισμένες λωρίδες κοτόπουλου','Tiras de pollo empanadas','Panierte Hähnchenstreifen','Aiguillettes de poulet panées'], ['Pita artigianale vuota, ideale per accompagnare i piatti','Plain handmade pita, ideal with the main dishes','Χειροποίητη σκέτη πίτα, ιδανική για συνοδευτικό','Pita artesanal sola, ideal para acompañar los platos','Handgemachtes Pitabrot, ideal als Beilage','Pita artisanale nature, idéale pour accompagner les plats'],
    ['4 polpettine di melanzane e formaggio fritte, servite con tzatziki','4 fried aubergine and cheese croquettes, served with tzatziki','4 τηγανητοί μελιτζανοκεφτέδες με τυρί, με τζατζίκι','4 croquetas fritas de berenjena y queso, con tzatziki','4 frittierte Auberginen-Käse-Bällchen mit Tzatziki','4 croquettes frites d’aubergine et fromage avec tzatziki'], ['Patate fritte croccanti','Crispy French fries','Τραγανές τηγανητές πατάτες','Patatas fritas crujientes','Knusprige Pommes frites','Frites croustillantes']
  ];

  const sizeDescriptions = {
    'Salsa Aris, porzione grande':['Aris sauce, large portion','Σάλτσα Άρης, μεγάλη μερίδα','Salsa Aris, porción grande','Aris-Sauce, große Portion','Sauce Aris, grande portion'],
    'Salsa al curry, porzione grande':['Curry sauce, large portion','Σάλτσα κάρυ, μεγάλη μερίδα','Salsa curry, porción grande','Currysauce, große Portion','Sauce curry, grande portion'],
    'Yogurt greco al naturale, porzione grande':['Plain Greek yoghurt, large portion','Γιαούρτι σκέτο, μεγάλη μερίδα','Yogur griego natural, porción grande','Griechischer Naturjoghurt, große Portion','Yaourt grec nature, grande portion'],
    'Salsa tzatziki, porzione piccola':['Tzatziki sauce, small portion','Τζατζίκι, μικρή μερίδα','Salsa tzatziki, porción pequeña','Tzatziki, kleine Portion','Tzatziki, petite portion'],
    'Salsa tirokafteri, porzione piccola':['Tirokafteri sauce, small portion','Τυροκαυτερή, μικρή μερίδα','Salsa tirokafteri, porción pequeña','Tirokafteri, kleine Portion','Tirokafteri, petite portion'],
    'Salsa Aris, porzione piccola':['Aris sauce, small portion','Σάλτσα Άρης, μικρή μερίδα','Salsa Aris, porción pequeña','Aris-Sauce, kleine Portion','Sauce Aris, petite portion'],
    'Hummus, porzione piccola':['Hummus, small portion','Χούμους, μικρή μερίδα','Hummus, porción pequeña','Hummus, kleine Portion','Houmous, petite portion'],
    'Melitzanosalata, porzione piccola':['Melitzanosalata, small portion','Μελιτζανοσαλάτα, μικρή μερίδα','Melitzanosalata, porción pequeña','Melitzanosalata, kleine Portion','Melitzanosalata, petite portion'],
    'Salsa al curry, porzione piccola':['Curry sauce, small portion','Σάλτσα κάρυ, μικρή μερίδα','Salsa curry, porción pequeña','Currysauce, kleine Portion','Sauce curry, petite portion'],
    'Yogurt greco naturale, porzione piccola':['Plain Greek yoghurt, small portion','Γιαούρτι σκέτο, μικρή μερίδα','Yogur griego natural, porción pequeña','Griechischer Naturjoghurt, kleine Portion','Yaourt grec nature, petite portion'],
    'Yogurt greco con miele':['Greek yoghurt with honey','Ελληνικό γιαούρτι με μέλι','Yogur griego con miel','Griechischer Joghurt mit Honig','Yaourt grec au miel'],
    'Bistecche di suino con patatine fritte':['Pork steaks with fries','Χοιρινές μπριζόλες με πατάτες','Filetes de cerdo con patatas fritas','Schweinesteaks mit Pommes','Steaks de porc avec frites'],
    'Pita vegetariana in stile greco.':['Greek-style vegetarian pita.','Χορτοφαγική πίτα ελληνικού τύπου.','Pita vegetariana al estilo griego.','Vegetarische Pita nach griechischer Art.','Pita végétarienne à la grecque.'],
    'Yogurt greco con miele e noci — il dessert greco per eccellenza':['Greek yoghurt with honey and walnuts — the classic Greek dessert','Ελληνικό γιαούρτι με μέλι και καρύδια — το κλασικό ελληνικό επιδόρπιο','Yogur griego con miel y nueces — el postre griego por excelencia','Griechischer Joghurt mit Honig und Walnüssen — der griechische Dessertklassiker','Yaourt grec au miel et aux noix — le dessert grec par excellence'],
    'Pita con pollo e farcitura ARGO':['Pita with chicken and ARGO fillings','Πίτα με κοτόπουλο και γέμιση ARGO','Pita con pollo y relleno ARGO','Pita mit Hähnchen und ARGO-Füllung','Pita au poulet et garniture ARGO'],
    'Pita con carne di suino e farcitura ARGO':['Pita with pork and ARGO fillings','Πίτα με χοιρινό και γέμιση ARGO','Pita con cerdo y relleno ARGO','Pita mit Schweinefleisch und ARGO-Füllung','Pita au porc et garniture ARGO'],
    'Ketchup':['Ketchup','Κέτσαπ','Kétchup','Ketchup','Ketchup'],
    'Maionese':['Mayonnaise','Μαγιονέζα','Mayonesa','Mayonnaise','Mayonnaise']
  };

  const groupRows = [['Rimuovi ingredienti','Remove ingredients','Αφαίρεση υλικών','Quitar ingredientes','Zutaten abwählen','Retirer des ingrédients'],['Salsa','Sauce','Σάλτσα','Salsa','Sauce','Sauce'],['Extra','Extras','Έξτρα','Extras','Extras','Suppléments']];
  const optionRows = [['Doppia salsa','Double sauce','Διπλή σάλτσα','Salsa doble','Doppelte Sauce','Double sauce'],['Tzatziki','Tzatziki','Τζατζίκι','Tzatziki','Tzatziki','Tzatziki'],['Tirokafteri','Tirokafteri','Τυροκαυτερή','Tirokafteri','Tirokafteri','Tirokafteri'],['Senza cipolla','No onion','Χωρίς κρεμμύδι','Sin cebolla','Ohne Zwiebel','Sans oignon'],['Senza pomodoro','No tomato','Χωρίς ντομάτα','Sin tomate','Ohne Tomate','Sans tomate'],['Senza salsa','No sauce','Χωρίς σάλτσα','Sin salsa','Ohne Sauce','Sans sauce'],['Senza insalata','No salad','Χωρίς σαλάτα','Sin ensalada','Ohne Salat','Sans salade'],['Senza patate','No fries','Χωρίς πατάτες','Sin patatas','Ohne Pommes','Sans frites']];
  const codes = ['it','en','el','es','de','fr'];
  function build(rows) { const out = {}; rows.forEach(row => { out[row[0]] = {}; codes.forEach((code, i) => { out[row[0]][code] = row[i]; }); }); return out; }
  const categories = build(categoryRows), names = build(nameRows), descriptions = build(descRows), groups = build(groupRows), options = build(optionRows);
  Object.entries(sizeDescriptions).forEach(([key, values]) => { descriptions[key] = { it: key }; codes.slice(1).forEach((code, i) => { descriptions[key][code] = values[i]; }); });

  window.ARGO_I18N = { languages, ui, categories, names, descriptions, groups, options };
})();
