plugins { id 'com.android.application' }

android {
    namespace 'it.argogreek.orders'
    compileSdk 35

    defaultConfig {
        applicationId 'it.argogreek.orders'
        minSdk 24
        targetSdk 25
        versionCode 3
        versionName '1.0.2-v2'
    }
}

dependencies {
    implementation 'com.sunmi:printerlibrary:1.0.24'
}
