plugins { id 'com.android.application' }

android {
    namespace 'it.argogreek.orders'
    compileSdk 35
    defaultConfig {
        applicationId 'it.argogreek.orders'
        minSdk 24
        targetSdk 28
        versionCode 1
        versionName '1.0.0'
    }
}

dependencies {
    implementation 'com.sunmi:printerlibrary:1.0.24'
}
