name: ARGO workflow test

on:
  push:
    paths:
      - '.github/workflows/argo-homepage-patch.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo "ARGO workflow OK"
